import { Agbalumo, Dosis } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";

const agbalumo = Agbalumo({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-agbalumo",
});
const dosis = Dosis({
  subsets: ["latin"],
  variable: "--font-dosis",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <Navbar />
      </header>
      <body className={`${agbalumo.variable} ${dosis.variable} font-primary`}>
        {children}
      </body>
    </html>
  );
}
